### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by michelleplur** [swarmcity/terminal-ts#1]
- [ ] Set up a TS react app
- [ ] Add web3 integrations
- [ ] Add styling solution so the app is skinnable
- [ ] Add basic routing system
- [ ] Add demo pages (/1, /2, /3 or with a hashrouter (```/#1, /#2, /#3```)
- [ ] Page 1 shows the current blocknumber 
- [ ] Page 2 shows a 12 word mnemonic
- [ ] Page 3 shows a meme of choice

**Comment by filoozom** [comment]
How skinnable do you want it to be? Just apply different colors, or being able to write a completely separate theme and "inject" the functionality in it?

**Comment by michelleplur** [comment]
The layout would always stay the same. The theme is colors and fonts.

**Comment by filoozom** [comment]
Alright, and do we have an idea in mind for the layout? Or should I just write something super basic?

I guess we can just use CSS variables if it's just about colors and fonts, which should be trivial.

**Comment by michelleplur** [comment]
Yes, you can see the exact UX here: https://github.com/swarmcity/SwarmCityConcept

**Comment by michelleplur** [comment]
Done
