### ISSUE TITLE
Avatar uploading and cropping

### ISSUE THREAD

**Issue by michelleplur** [swarmcity/terminal-ts#6]
As a user I want to be able to add, crop, and replace an image in Swarm City Terminal.
<img width="239" alt="Screen Shot 2022-03-11 at 1 34 40 PM" src="https://user-images.githubusercontent.com/30149603/157930949-242b807f-1c49-4ce5-b5c0-88b6286bfcd7.png">

<img width="243" alt="Screen Shot 2022-03-11 at 1 34 50 PM" src="https://user-images.githubusercontent.com/30149603/157930959-94243d33-5988-4943-b524-361b35164a58.png">

**Comment by filoozom** [comment]
Should I use [this](https://github.com/swarmcity/terminal-ts/pull/11/files#diff-8a68936f6c338141ae240e78307606c7d8909a98bb1fbc8c1de3abddff46c380) as the default avatar? Or the one shown in your screenshots?

**Comment by michelleplur** [comment]
![image](https://user-images.githubusercontent.com/52613476/166506026-22e41a22-a531-4e92-9e7e-7141cb154905.png)

^^^ please use this one 
And it's indeed rounded.
